[package]
name = "bench_curves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
curv-kzen = { version = "0.10.0", features = ["num-bigint"], default-features = false }
criterion = { version = "0.4", features = ["html_reports"] }
elliptic-curve = { version = "0.13.4", features = ["arithmetic", "group"] }
crypto-bigint = "0.5.1"

[[bench]]
name = "curv_benches"
harness = false

[[bench]]
name = "crypto_bigint_benches"
harness = false
